## PyTorch Tutorial #02 - Tensor Basics

In [1]:
import torch

In [22]:
x = torch.empty((2,2))
x

tensor([[1.7556e+24, 9.9632e-43],
        [1.7556e+24, 9.9632e-43]])

In [31]:
x = torch.rand((2,2))
x

tensor([[0.5112, 0.9370],
        [0.8605, 0.9141]])

In [32]:
x = torch.zeros((2,2))
x

tensor([[0., 0.],
        [0., 0.]])

In [33]:
x = torch.ones((2,2))
x

tensor([[1., 1.],
        [1., 1.]])

In [35]:
x = torch.ones((2,2), dtype = torch.int)
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [37]:
x = torch.ones((2,2), dtype = torch.double)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [39]:
x = torch.ones((2,2), dtype = torch.float16)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [41]:
x.size()

torch.Size([2, 2])

In [45]:
x.shape

torch.Size([2, 2])

In [47]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

### Operaciones básicas

In [49]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x + y
z

tensor([[0.1912, 1.3545],
        [1.1781, 1.4141]])

In [51]:
z = torch.add(x,y)
z

tensor([[0.1912, 1.3545],
        [1.1781, 1.4141]])

In [53]:
# EN pytorch, todas las funciones con guión bajo (_) modifican la variable actual.
# Es decir, no es necesario alojar en otra variable y = y + x.
y.add_(x)
y

tensor([[0.2008, 1.7601],
        [1.5731, 2.2939]])

In [54]:
z = x - y
z

tensor([[-0.1912, -1.3545],
        [-1.1781, -1.4141]])

In [55]:
z = torch.sub(x, y)
z

tensor([[-0.1912, -1.3545],
        [-1.1781, -1.4141]])

In [57]:
z = x * y
z

tensor([[1.9187e-03, 7.1380e-01],
        [6.2135e-01, 2.0182e+00]])

In [58]:
z = torch.mul(x, y)
z

tensor([[1.9187e-03, 7.1380e-01],
        [6.2135e-01, 2.0182e+00]])

In [59]:
y.mul_(x)

tensor([[1.9187e-03, 7.1380e-01],
        [6.2135e-01, 2.0182e+00]])

In [60]:
z = x / y
z

tensor([[4.9807, 0.5682],
        [0.6357, 0.4359]])

In [61]:
z = torch.div(x, y)
z

tensor([[4.9807, 0.5682],
        [0.6357, 0.4359]])

### Slicing

In [62]:
x = torch.rand(5, 3)
x

tensor([[0.7600, 0.9401, 0.9755],
        [0.2668, 0.2241, 0.1016],
        [0.2840, 0.8831, 0.9596],
        [0.6166, 0.7299, 0.6360],
        [0.7198, 0.0763, 0.2631]])

In [63]:
x[:,0]

tensor([0.7600, 0.2668, 0.2840, 0.6166, 0.7198])

In [65]:
x[1, 1]

tensor(0.2241)

In [66]:
# con .item() llamás al número que tenés dentro del tensor, pero solo funciona si hay un solo número.
x[1, 1].item()

0.2241424322128296

### View y Reshape

In [68]:
x = torch.rand(4,4)
x

tensor([[0.7602, 0.1275, 0.1322, 0.2943],
        [0.7116, 0.9081, 0.2689, 0.4111],
        [0.5147, 0.6365, 0.5886, 0.9670],
        [0.7418, 0.2538, 0.7469, 0.3912]])

In [71]:
# En view tenés que poner la misma cantidad de elementos que el tensor.
y = x.view(16)
y

tensor([0.7602, 0.1275, 0.1322, 0.2943, 0.7116, 0.9081, 0.2689, 0.4111, 0.5147,
        0.6365, 0.5886, 0.9670, 0.7418, 0.2538, 0.7469, 0.3912])

In [75]:
y = x.view(-1, 8)
y

tensor([[0.7602, 0.1275, 0.1322, 0.2943, 0.7116, 0.9081, 0.2689, 0.4111],
        [0.5147, 0.6365, 0.5886, 0.9670, 0.7418, 0.2538, 0.7469, 0.3912]])

In [76]:
# View crea una visualización de un tensor con otras dimensiones, y Reshape crea una copia.
# Es decir, si cambio algo en View, se cambia en el tensor original; en cambio es Reshape no.

### Pasar de NumPy a tensor Torch

In [77]:
import numpy as np

In [78]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [80]:
b = a.numpy()
type(b)

numpy.ndarray

In [81]:
# Si transformo un tensor torch a un vector numpy, al modificar uno, se modifica le otro también, porque ambos comparten la misma unidad en la memoria.

In [83]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [85]:
b = torch.from_numpy(a)
type(b)

torch.Tensor

In [88]:
# Por ejemplo, acá modifico el tensor a y también se modifica el tensor b.
a += 1
b

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

### Mover los tensores a la GPU

In [98]:
# Solo funciona en Windows, y si está el CUDA toolkit instalado.
device = 'cpu'
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device = device)

In [99]:
# Se puede crear directamente en la GPU, como en la celda anterior.
# O se puedew crear en la CPU y moverlo a la GPU como se muestra ahora:
y = torch.ones(5)
y = y.to(device)

In [102]:
# Si intento transformar un tensor alojado en la GPU a numpy va a arrojar error porque numpy solo trabaja en CPU.
# Por eso, primero se debe mover el tensor a la CPU y después se transforma a numpy.
x = torch.ones(5)
z = x * y
z = z.to('cpu')