## PyTorch Tutorial #10 - Dataset Transforms

In [16]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [2]:
# Todas las transformaciones de PyTorch
# https://pytorch.org/docs/stable/torchvision/transforms.html

# Las transformaciones pueden ser aplicadas a imágenes PIL, tensores, ndarrays 
# o custom data durante la creación de Dataset

### Ejemplo de implementación de Custom Transform con clases.

In [6]:
class WineDataSet(Dataset):
    def __init__(self, transform = None):
        # data loading
        xy = np.loadtxt('./data/wine/wine.csv', delimiter = ',', dtype = np.float32, skiprows = 1)
        self.n_samples = xy.shape[0]

        # Note that we do not convert to tensor here
        self.x = xy[:, 1:]
        self.y = xy[:, [0]] # n_samples, 1

        self.transform = transform        

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        
        return sample

    def __len__(self):
        return self.n_samples

In [11]:
# Custom transform
class ToTensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [8]:
dataset = WineDataSet(transform = ToTensor())
first_data = dataset[0]
features, labels = first_data

In [9]:
features, labels

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

### Ejemplo de implementación de varias Custom Transform con clases.

In [13]:
# Custom transform
class MulTransform:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, target = sample
        inputs *= self.factor
        return inputs, target

In [19]:
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(2)])

In [20]:
dataset = WineDataSet(transform = composed)
first_data = dataset[0]
features, labels = first_data

In [21]:
features, labels

(tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
         6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
         2.1300e+03]),
 tensor([1.]))